// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://telfcgxqzoqxauhpjhig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbGZjZ3hxem9xeGF1aHBqaGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzUzNzIsImV4cCI6MjA2OTgxMTM3Mn0.4xZs9LaenUHew4oPRDJLAM4I1BM3YHbO--SWbaO_aac";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});